# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "cova-0.10.1-_OE4R3W-BACeoTJcwNwzTBmVKvQ5Eh6x6f6C-7Cl3vf1";
    path = fetchzip {
      url = "https://codeload.github.com/aaronjheng/cova/tar.gz/175bd6c03c2e8d7de8b1536333f1ec3a63b9518d";
      hash = "sha256-5XMNEAYpy+u5EEhCiu5r8rcIAc/qXDltoZIp2PwOBfs=";
    };
  }
  {
    name = "dotenv-0.3.0-hfaNFtm3AACGiIZx5jDPHB4Q1QGs9BEMKH-sq32ZxRXa";
    path = fetchzip {
      url = "https://codeload.github.com/dying-will-bullet/dotenv/tar.gz/f6dff7ce2c39ceaafd00114c7d0674376cd82b87";
      hash = "sha256-GsK7SBqREQmpKKW6PSCenrX3G8PUZW7hdhvu7fSq/PE=";
    };
  }
]
