# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "cova-0.10.1-_OE4Rxe9BADFRKg2oUBnAjKWa82Vo5Depu89hLH6uuLM";
    path = fetchgit {
      url = "https://github.com/aaronjheng/cova";
      rev = "29574f6b94802e0dfa298b16fb817226256eb356";
      hash = "sha256-faiRJDAAohAUv2Vr3ACeAnxJEoPMSHXdAwZN2NndtlE=";
    };
  }
  {
    name = "dotenv-0.3.0-hfaNFtm3AACGiIZx5jDPHB4Q1QGs9BEMKH-sq32ZxRXa";
    path = fetchgit {
      url = "https://github.com/dying-will-bullet/dotenv";
      rev = "f6dff7ce2c39ceaafd00114c7d0674376cd82b87";
      hash = "sha256-GsK7SBqREQmpKKW6PSCenrX3G8PUZW7hdhvu7fSq/PE=";
    };
  }
]
